// <auto-generated />
using System;
using APIStreamingDeAudio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIStreamingDeAudio.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("APIStreamingDeAudio.Models.FaixaAudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaminhoDoArquivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ContemConteudoExplicito")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataDeLancamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDeUpload")
                        .HasColumnType("TEXT");

                    b.Property<int>("DuracaoEmSegundos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FormatoArquivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FrequenciaAmostragem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GeneroMusical")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeAlbum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeArtista")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCompositor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeGravadora")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TamanhoArquivoBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaxaDeBits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalReproducoes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FaixasAudio");
                });
#pragma warning restore 612, 618
        }
    }
}
